### ISSUE TITLE
Add facebook analytics pixel

### ISSUE THREAD

**Issue by lucymk** [InFact-coop/create-refresh#25]
add Aaron's changes (tracking different event) if possible

**Comment by lucymk** [comment]
@aaronparr please let us know the details for this

**Comment by aaronparr** [comment]
Here is a doc with the events we would like to record on GA and FB. It's just the one on Facebook, but there's a few for GA. It would also be interesting to know at what point they signed up too (before they uploaded, after, or in-between...) Also apologies if this isn't the best format. It was how I was requested to lay out pixels for a previous website, but that project has since been criticised for having a messy GA pixel.... https://docs.google.com/spreadsheets/d/1PNQOiV1r2BpN8L9eR55U8RzHDLFQKmiSL0GlObIDzCQ/edit?usp=sharing

here is the GA pixel code:


<script async src="https://www.googletagmanager.com/gtag/js?id=UA-108065136-4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-108065136-4');
</script>

here is the FB pixel code:


<script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '586710681772306');
  fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=586710681772306&ev=PageView&noscript=1"
/></noscript>


let me know if there's anything else you need or need access to!

**Comment by developess** [comment]
Hi @aaronparr 

Happy new year :) Thank you for this info! We have added the code you shared with us which adds the facebook and google analytics pixels. However, to track the data requested in the google sheet, I think we (or you) need to setup a Google Tag Manager Container for this site and attach the tags and triggers correctly to these events. 

I think we may also need to add the Google Tag Manager code snippets to the site. Is this something you are expecting us to do or will it be done by someone on your side?

Let us know! 

Thanks, Jessie

**Comment by aaronparr** [comment]
Hey Jessie!

Happy new year to you too! I'm not familiar with doing is so it would be ideal if you were able to do it. If I set up a Google Tag Manager Container (after figuring out how to do that first) and gave you access, would that work?

**Comment by lucymk** [comment]
@aaronparr yes that would be great! just email me the details once you've done that

**Comment by aaronparr** [comment]
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PHXNVJF');</script>



<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PHXNVJF"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>


@lucymk I've added you as an admin to the tag manager and the pixel manager. Let me know whether you want me to add anyone else or if there's anything else I need to do to connect it to the pixel/tag manager.

**Comment by lucymk** [comment]
all added
